# Generated by Django 5.2.7 on 2025-12-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventario", "0008_cpu_gpu_componentes"),
        ("app_inventario", "0008_factura"),
    ]

    operations = []
