# Generated by Django 5.2.7 on 2025-12-16 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventario", "0009_merge_0008_cpu_gpu_componentes_0008_factura"),
    ]

    operations = [
        migrations.RenameField(
            model_name="factura",
            old_name="archivo",
            new_name="archivo_factura",
        ),
        migrations.RenameField(
            model_name="factura",
            old_name="fecha",
            new_name="fecha_compra",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="creado_por",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="descripcion",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="monto_total",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="productos",
        ),
        migrations.RemoveField(
            model_name="productos",
            name="documento_factura",
        ),
        migrations.AddField(
            model_name="factura",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productos",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="productos",
                to="app_inventario.factura",
            ),
        ),
        migrations.AddField(
            model_name="productos",
            name="valor_compra",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
