# Generated by Django 5.2.7 on 2025-12-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventario", "0010_rename_archivo_factura_archivo_factura_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productos",
            name="factura",
        ),
        migrations.RemoveField(
            model_name="productos",
            name="valor_compra",
        ),
        migrations.AddField(
            model_name="productos",
            name="documento_factura",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productos",
            name="precio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Precio Unitario",
            ),
        ),
        migrations.CreateModel(
            name="Facturas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_factura",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Número de Factura"
                    ),
                ),
                ("fecha_emision", models.DateField()),
                (
                    "monto_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto Total"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="facturas/"),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facturas",
                        to="app_inventario.proveedores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Factura",
                "verbose_name_plural": "Facturas",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.AddField(
            model_name="productos",
            name="facturas",
            field=models.ManyToManyField(
                blank=True,
                related_name="productos",
                to="app_inventario.facturas",
                verbose_name="Facturas asociadas",
            ),
        ),
        migrations.DeleteModel(
            name="Factura",
        ),
    ]
