# Generated by Django 5.2.7 on 2025-12-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventario", "0011_remove_productos_factura_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productos",
            name="documento_factura",
        ),
        migrations.RemoveField(
            model_name="productos",
            name="precio",
        ),
        migrations.AddField(
            model_name="productos",
            name="valor_compra",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
