# Generated by Django 5.2.7 on 2025-12-17 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventario", "0012_remove_productos_documento_factura_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturas",
            name="proveedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facturas",
                to="app_inventario.proveedores",
            ),
        ),
        migrations.AlterField(
            model_name="productos",
            name="facturas",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="productos",
                to="app_inventario.facturas",
                verbose_name="Facturas asociadas",
            ),
        ),
    ]
