# Generated by Django 5.2.7 on 2025-12-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inventario", "0013_alter_facturas_proveedor_alter_productos_facturas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productos",
            name="estado_garantia",
            field=models.CharField(
                choices=[
                    ("VIGENTE", "Vigente"),
                    ("POR_VENCER", "Por Vencer"),
                    ("VENCIDA", "Vencida"),
                    ("NO_APLICA", "No aplica"),
                ],
                default="VIGENTE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productos",
            name="facturas",
            field=models.ManyToManyField(
                blank=True,
                related_name="productos",
                to="app_inventario.facturas",
                verbose_name="Facturas asociadas",
            ),
        ),
        migrations.AlterField(
            model_name="productos",
            name="fecha_venc_garantia",
            field=models.DateField(
                blank=True, null=True, verbose_name="Vencimiento Garantía"
            ),
        ),
        migrations.AlterField(
            model_name="productos",
            name="garantia_meses",
            field=models.PositiveIntegerField(
                default=12, verbose_name="Meses de Garantía"
            ),
        ),
    ]
